// fuzz_scan.cpp — libFuzzer entry point.
// Feeds fuzzer-generated bytes to the full scan pipeline with every real
// signature loaded, exercising each validator's header parsing on adversarial
// input. This is the "fuzz the parsers from day one" guardrail from
// phase2-design §9.
//
// Build (from the moria dir):
//   clang++ -std=c++20 -O1 -g -fsanitize=fuzzer,address -I src -I third_party \
//     -DFT_FUZZ_SIGDIR=\"$PWD/signatures\" \
//     src/scan.cpp src/ahocorasick.cpp src/resolve.cpp src/expr.cpp \
//     src/layout.cpp src/sigload.cpp src/validators/*.cpp fuzz/fuzz_scan.cpp \
//     -o fuzz_scan
// Run: ./fuzz_scan -max_total_time=60
#include <cstddef>
#include <cstdint>
#include <span>

#include "archives.hpp"
#include "reader.hpp"
#include "scan.hpp"
#include "secrets.hpp"
#include "sigload.hpp"

#ifndef FT_FUZZ_SIGDIR
#define FT_FUZZ_SIGDIR "signatures"
#endif

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    static const ft::LoadResult sigs = ft::load_signatures(FT_FUZZ_SIGDIR);
    ft::Reader reader(std::span<const uint8_t>(data, size));
    auto findings = ft::scan(reader, sigs.signatures);
    for (auto& f : findings) ft::list_members(reader, f);  // exercise archive listers
    auto secrets = ft::scan_secrets(reader);
    (void)findings;
    (void)secrets;
    return 0;
}
