// Build helper: read every signatures*/*.toml file and create a C++ source file
// containing those rules. This lets moria run without a separate rules folder.
// CMake runs this helper; it is not included in the released program.
//
// Usage: embed_sigs <out.cpp> <curated_dir> <firmware_dir> <generated_dir>
//
// Each TOML file is stored as an unchanged C++ string. The new file defines the
// three functions declared in sigload.hpp.
#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static const char* kDelim = "MORIA_EMBED";  // raw-string delimiter

static std::string read_file(const fs::path& p) {
    std::ifstream f(p, std::ios::binary);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

// List *.toml files directly inside `dir`, sorted the same way on every run.
static std::vector<fs::path> toml_files(const fs::path& dir) {
    std::vector<fs::path> out;
    std::error_code ec;
    if (fs::is_directory(dir, ec))
        for (const auto& e : fs::directory_iterator(dir))
            if (e.is_regular_file() && e.path().extension() == ".toml") out.push_back(e.path());
    std::sort(out.begin(), out.end());
    return out;
}

int main(int argc, char** argv) {
    if (argc != 5) {
        std::fprintf(stderr, "usage: %s <out.cpp> <curated> <firmware> <generated>\n", argv[0]);
        return 2;
    }
    const char* out_path = argv[1];
    const char* set_dirs[3] = {argv[2], argv[3], argv[4]};
    const char* set_fn[3] = {"embedded_curated", "embedded_firmware", "embedded_generated"};
    const char* set_var[3] = {"kCurated", "kFirmware", "kGenerated"};

    std::ostringstream o;
    o << "// GENERATED by tools/embed_sigs.cpp - do not edit.\n"
         "#include \"sigload.hpp\"\n#include <iterator>\nnamespace ft {\nnamespace {\n";

    int blob = 0;
    std::vector<std::vector<std::pair<std::string, int>>> sets(3);  // (name, blob id)
    for (int s = 0; s < 3; ++s) {
        for (const fs::path& p : toml_files(set_dirs[s])) {
            std::string data = read_file(p);
            std::string close = std::string(")") + kDelim + "\"";
            if (data.find(close) != std::string::npos) {
                std::fprintf(stderr, "embed_sigs: %s contains the raw-string delimiter\n",
                             p.string().c_str());
                return 1;
            }
            o << "static constexpr char b" << blob << "[] = R\"" << kDelim << "(" << data << ")"
              << kDelim << "\";\n";
            sets[s].push_back({p.filename().string(), blob});
            ++blob;
        }
    }

    for (int s = 0; s < 3; ++s) {
        o << "static constexpr EmbeddedToml " << set_var[s] << "[] = {";
        for (const auto& [name, id] : sets[s])
            o << "{\"" << name << "\", b" << id << ", sizeof(b" << id << ") - 1},";
        o << "};\n";
    }
    o << "}  // namespace\n";
    for (int s = 0; s < 3; ++s)
        o << "std::span<const EmbeddedToml> " << set_fn[s] << "() { return {" << set_var[s]
          << ", std::size(" << set_var[s] << ")}; }\n";
    o << "}  // namespace ft\n";

    std::ofstream(out_path, std::ios::binary) << o.str();
    return 0;
}
